backend:
  name: git-gateway
  branch: main
  repo: YOUR_USERNAME/balajiganapathy-website

media_folder: media
public_folder: /media
site_url: https://balajiganapathy.com

collections:
  # Collection 0: Site Settings (File collection)
  - name: site
    label: Site Settings
    description: Global site configuration
    folder: _data
    format: json
    create: false
    delete: false
    extension: json
    filter:
      field: _id
      value: config
    files:
      - name: config
        label: Site Configuration
        file: _data/config.json
        description: Global site metadata and settings
        fields:
          - { label: "Site Title", name: "title", widget: "string", default: "Balaji Ganapathy" }
          - { label: "Tagline", name: "tagline", widget: "string", default: "Global Social Impact Executive" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "LinkedIn", name: "linkedin", widget: "string" }

  # Collection 1: Leader Persona (File collection)
  - name: leader
    label: Leader Page
    description: Leader persona content and configuration
    folder: _data
    format: json
    create: false
    delete: false
    files:
      - name: leader
        label: Leader Content
        file: _data/leader.json
        description: Complete leader persona data
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Leader" }
          - { label: "Hero Tagline", name: "tagline", widget: "string", default: "Empowering Purpose. Enabling Impact. Transforming Leadership." }
          - { label: "Hero Subtitle", name: "subtitle", widget: "string", default: "25+ Years Transforming Global Impact" }
          - { label: "Accent Color", name: "colorAccent", widget: "color", default: "#00D8BE" }
          - label: "Featured Programs"
            name: "programs"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Program Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icon", name: "icon", widget: "string", default: "⭐" }
          - label: "Speaking Topics"
            name: "speakingTopics"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Topic Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Book Strategic Advisory Call" }
          - { label: "CTA Color", name: "ctaColor", widget: "color", default: "#00D8BE" }

  # Collection 2: Speaker Persona (File collection)
  - name: speaker
    label: Speaker Page
    description: Speaker persona and engagements
    folder: _data
    format: json
    create: false
    delete: false
    files:
      - name: speaker
        label: Speaker Content
        file: _data/speaker.json
        description: Complete speaker persona data
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Speaker" }
          - { label: "Hero Tagline", name: "tagline", widget: "string", default: "Keynotes on Leadership, Impact & Transformation" }
          - { label: "Accent Color", name: "colorAccent", widget: "color", default: "#FFB400" }
          - label: "Speaking Topics"
            name: "topics"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Topic Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Details", name: "details", widget: "text" }
          - label: "Featured Engagements"
            name: "engagements"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Event Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Event Type", name: "type", widget: "string", default: "Conference" }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Book for Your Conference" }
          - { label: "CTA Color", name: "ctaColor", widget: "color", default: "#FFB400" }

  # Collection 3: Advisor Persona (File collection)
  - name: advisor
    label: Advisor Page
    description: Advisor persona, expertise, testimonials and case studies
    folder: _data
    format: json
    create: false
    delete: false
    files:
      - name: advisor
        label: Advisor Content
        file: _data/advisor.json
        description: Complete advisor persona data
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Advisor" }
          - { label: "Hero Tagline", name: "tagline", widget: "string", default: "Strategic Advisory for ESG & Social Impact" }
          - { label: "Accent Color", name: "colorAccent", widget: "color", default: "#00D8BE" }
          - label: "Expertise Areas"
            name: "expertise"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Area Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
          - label: "Case Studies"
            name: "caseStudies"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Request Consulting Engagement" }
          - { label: "CTA Color", name: "ctaColor", widget: "color", default: "#00D8BE" }

  # Collection 4: Coach Persona (File collection)
  - name: coach
    label: Coach Page
    description: Coach persona, packages and transformation stories
    folder: _data
    format: json
    create: false
    delete: false
    files:
      - name: coach
        label: Coach Content
        file: _data/coach.json
        description: Complete coach persona data
        fields:
          - { label: "Page Title", name: "title", widget: "string", default: "Coach" }
          - { label: "Hero Tagline", name: "tagline", widget: "string", default: "Transforming Leaders, Teams & Organizations" }
          - { label: "Accent Color", name: "colorAccent", widget: "color", default: "#FFD700" }
          - label: "Coaching Focus Areas"
            name: "focusAreas"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Focus Area", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Transformation Stories"
            name: "transformationStories"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Story Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Coaching Packages"
            name: "packages"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Package Name", name: "name", widget: "string" }
              - { label: "Duration", name: "duration", widget: "string" }
              - { label: "Sessions", name: "sessions", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Schedule Free 30-min Intro" }
          - { label: "CTA Color", name: "ctaColor", widget: "color", default: "#FFD700" }
